import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google' // using this font from google
import localFont from 'next/font/local'
import NavBar from './NavBar'
import AuthProvider from './auth/Provider'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

// this is a function to which we give an options object, and subsets to specify only the characters we need 
const roboto = Roboto({
  subsets: ['latin'], weight: ['400', '500']
})

const poppins = localFont({
  src: '../public/fonts/poppins-regular-webfont.woff2',
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // for exposing to social media eg:'
  openGraph: {
    title: '...', 
    description: '...'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter"> 
      {/* <Script async src="" */}
      <body className={poppins.variable}>
        <AuthProvider>
          <NavBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
